# Generated by Django 5.1.7 on 2025-03-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=10)),
                ('download_count', models.IntegerField(default=0)),
                ('cover_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
