# Generated by Django 4.2.20 on 2025-03-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("document_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TermDocumentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tf", models.FloatField(default=0.0)),
                ("tfidf", models.FloatField(default=0.0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.book"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.term"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["term"], name="api_termdoc_term_id_db15cd_idx"
                    ),
                    models.Index(
                        fields=["document"], name="api_termdoc_documen_7d6fbb_idx"
                    ),
                ],
                "unique_together": {("term", "document")},
            },
        ),
    ]
